### ISSUE TITLE
Scraper run ok locally but not on morph

### ISSUE THREAD

**Issue by LoveMyData** [openaustralia/morph#1088]
https://morph.io/LoveMyData/wollondilly

```
Injecting configuration and compiling...
Injecting scraper and running...
 Scraping from 01/08/2016 to 31/08/2016, changable via MORPH_PERIOD variable
 /app/vendor/ruby-2.0.0/lib/ruby/2.0.0/net/http.rb:921:in `connect': SSL_connect returned=1 errno=0 state=unknown state: unknown protocol (OpenSSL::SSL::SSLError)
    from /app/vendor/ruby-2.0.0/lib/ruby/2.0.0/net/http.rb:921:in `block in connect'
    from /app/vendor/ruby-2.0.0/lib/ruby/2.0.0/timeout.rb:52:in `timeout'
    from /app/vendor/ruby-2.0.0/lib/ruby/2.0.0/net/http.rb:921:in `connect'
    from /app/vendor/ruby-2.0.0/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
    from /app/vendor/ruby-2.0.0/lib/ruby/2.0.0/net/http.rb:857:in `start'
    from /app/vendor/bundle/ruby/2.0.0/gems/net-http-persistent-2.9.4/lib/net/http/persistent.rb:700:in `start'
    from /app/vendor/bundle/ruby/2.0.0/gems/net-http-persistent-2.9.4/lib/net/http/persistent.rb:631:in `connection_for'
    from /app/vendor/bundle/ruby/2.0.0/gems/net-http-persistent-2.9.4/lib/net/http/persistent.rb:994:in `request'
    from /app/vendor/bundle/ruby/2.0.0/gems/mechanize-2.7.5/lib/mechanize/http/agent.rb:274:in `fetch'
    from /app/vendor/bundle/ruby/2.0.0/gems/mechanize-2.7.5/lib/mechanize.rb:464:in `get'
    from scraper.rb:25:in `<main>'
```

**Comment by LoveMyData** [comment]
Another scraper as an example:
https://github.com/planningalerts-scrapers/the_hills/issues/2
