### ISSUE TITLE
OSError: [Errno 24] Too many open files

### ISSUE THREAD

**Issue by Zoe1808** [openaustralia/morph#1200]
Command: mitmweb -p 8989 --web-iface 10.101.54.88 --no-web-open-brser --quiet
Run for a while and I got:
`Exception in thread ServerThread (('::', 8989, 0, 0)):

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 917, in _bootstrap_inner
  File "/home/wxqa/workspace/mitmproxy/mitmproxy/master.py", line 37, in run
  File "/home/wxqa/workspace/mitmproxy/mitmproxy/net/tcp.py", line 607, in serve_forever
  File "/usr/local/lib/python3.7/socket.py", line 212, in accept
OSError: [Errno 24] Too many open files`

mitmproxy version: 5.0.0.dev

**Comment by ianheggie-oaf** [comment]
Closed as it seems stale and unrelated to morph
