### ISSUE TITLE
Improve relevance of email alerts by adding "acknowledge" action

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/morph#1213]
The problem:

Email alerts of broken scrapers are a fantastic way to ensure that scrapers are maintainable. However, in the case of planningalerts we have a **lot** of scrapers and many of them (around 30 or 40) can be broken at any one time. It just isn't helpful to get an email alert one day that says have 38 broken scrapers and the next day get a message saying you have 39 broken scrapers. Is it one new broken scraper? Which one?

The fact that the subject line is roughly the same every day and the email alerts come every day means that in reality **I completely ignore them**. I suspect I'm not unusual in this in which case the current design of the email alerts **is completely broken** because it just doesn't serve its purpose.

A possible solution:
Add an "acknowledge" action next to every broken scraper in an email alert. When you acknowledge a broken scraper you're saying I've recorded that it's broken somewhere sensible and I don't want to get alerted about it (until it's fixed and then breaks again).

This would allow the user to truly see new interesting things.

Anyone can subscribe to get email alerts from any scraper so the acknowledge action needs to be a personal one. Everyone will have to do it for themselves.

**Comment by jamezpolley** [comment]
I am not sure if "Which is the new broken scraper" is such a big problem; from what I can see, it looks like the scrapers are already ordered by most-recently-broken. The email I'm looking at right now starts with one that has been erroring for 2 days, then one that's been erroring for 17 days, then several that have been erroring for 2 months..

I think it would be useful to see a breakdown by language (27 ruby, 12 python, 3 PHP) or even language version (15 Ruby 1.9, 3, Ruby 2.3, 2 Ruby 2.5). It looks like for most errors, the first line of the error message is relevant too, so I think it would be useful to have those summarised.

For instance, several scrapers in the email I'm looking at have something like this:

> /app/vendor/bundle/ruby/2.3.0/gems/rest-client-1.6.7/lib/restclient/abstract_response.rb:48:in `return!': 404 Resource Not Found (RestClient::ResourceNotFound)

If I'm suddenly seeing *all* the scrapers reporting a 404, I can be fairly sure it's not a problem with the scraper but a problem with mitmproxy.

Similarly, if every scraper has:

> /app/vendor/bundle/ruby/1.9.1/gems/net-http-persistent-2.5.2/lib/net/http/persistent/ssl_reuse.rb:70:in `connect': SSL_connect returned=1 errno=0 state=unknown state: unknown protocol (OpenSSL::SSL::SSLError)

I can be fairly sure there's an underlying SSL issue on the scraper platform rather than a problem with the scraper.
