### ISSUE TITLE
SSL errors from mitmproxy for eservices.gawler.sa.gov.au

### ISSUE THREAD

**Issue by jamezpolley** [openaustralia/morph#1218]
Reported at planningalerts-scrapers/town_of_gawler_sa_development_applications/issues/1

````
Retrieving page: https://eservices.gawler.sa.gov.au/eservice/daEnquiryInit.do?doc_typ=4&nodeNum=3228
{ StatusCodeError: 502 - "<html>\n            <head>\n                <title>502 Bad Gateway</title>\n            </head>\n            <body>\n            <h1>502 Bad Gateway</h1>\n            <p>Certificate verification error for eservices.gawler.sa.gov.au: unable to get local issuer certificate (errno: 20, depth: 0)</p>\n            </body>\n        </html>"
    at new StatusCodeError (/app/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/app/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/app/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/app/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/app/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
````

**Comment by jamezpolley** [comment]
This seems to be caused by improper configuration on the Council's web server; they are serving the root CA certificate and their own wildcard, but not the intermediate CA certificate that sits between those. mitmproxy has the root cert in its keystore, but not the intermediate CA, so it can't validate the whole chain and rejects the connection.

**Comment by jamezpolley** [comment]
I'm going to close this for now as I think mitmproxy is behaving correctly; but I'll re-open this if it turns out to be a broader problem. Perhaps there's a more complete set of certificates we could use?
