### ISSUE TITLE
Circular dependency problem on first few runs in background jobs

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/morph#193]
Here's an example

```
A RuntimeError occurred in background at 2014-02-19 23:00:13 UTC :

  Circular dependency detected while autoloading constant Morph::DockerRunner
  /var/www/shared/bundle/ruby/2.0.0/gems/activesupport-4.0.3/lib/active_support/dependencies.rb:461:in `load_missing_constant'

  -------------------------------
Backtrace:
-------------------------------

  /var/www/shared/bundle/ruby/2.0.0/gems/activesupport-4.0.3/lib/active_support/dependencies.rb:461:in `load_missing_constant'
  /var/www/shared/bundle/ruby/2.0.0/gems/activesupport-4.0.3/lib/active_support/dependencies.rb:184:in `const_missing'
  /var/www/releases/20140219225652/app/models/run.rb:101:in `go_with_logging'
  /var/www/releases/20140219225652/app/models/run.rb:121:in `go!'
  /var/www/releases/20140219225652/app/models/run.rb:129:in `synch_and_go!'
  /var/www/releases/20140219225652/app/workers/run_worker.rb:5:in `perform'
  /var/www/shared/bundle/ruby/2.0.0/gems/sidekiq-2.17.4/lib/sidekiq/processor.rb:49:in `block (3 levels) in process'
  /var/www/shared/bundle/ruby/2.0.0/gems/sidekiq-2.17.4/lib/sidekiq/middleware/chain.rb:122:in `call'
  /var/www/shared/bundle/ruby/2.0.0/gems/sidekiq-2.17.4/lib/sidekiq/middleware/chain.rb:122:in `block in invoke'
  /var/www/shared/bundle/ruby/2.0.0/gems/exception_notification-4.0.1/lib/exception_notification/sidekiq.rb:8:in `call'
  /var/www/shared/bundle/ruby/2.0.0/gems/sidekiq-2.17.4/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
  /var/www/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.7.2.195/lib/new_relic/agent/instrumentation/sidekiq.rb:30:in `block in call'
  /var/www/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.7.2.195/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:339:in `perform_action_with_newrelic_trace'
  /var/www/shared/bundle/ruby/2.0.0/gems/newrelic_rpm-3.7.2.195/lib/new_relic/agent/instrumentation/sidekiq.rb:21:in `call'
  /var/www/shared/bundle/ruby/2.0.0/gems/sidekiq-2.17.4/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
  /var/www/shared/bundle/ruby/2.0.0/gems/sidekiq-2.17.4/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
  /var/www/shared/bundle/ruby/2.0.0/gems/sidekiq-2.17.4/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
  /var/www/shared/bundle/ruby/2.0.0/gems/sidekiq-2.17.4/lib/sidekiq/middleware/server/retry_jobs.rb:62:in `call'
  /var/www/shared/bundle/ruby/2.0.0/gems/sidekiq-2.17.4/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
  /var/www/shared/bundle/ruby/2.0.0/gems/sidekiq-2.17.4/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
  /var/www/shared/bundle/ruby/2.0.0/gems/sidekiq-2.17.4/lib/sidekiq/logging.rb:22:in `with_context'
  /var/www/shared/bundle/ruby/2.0.0/gems/sidekiq-2.17.4/lib/sidekiq/middleware/server/logging.rb:7:in `call'
  /var/www/shared/bundle/ruby/2.0.0/gems/sidekiq-2.17.4/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
  /var/www/shared/bundle/ruby/2.0.0/gems/sidekiq-2.17.4/lib/sidekiq/middleware/chain.rb:127:in `call'
  /var/www/shared/bundle/ruby/2.0.0/gems/sidekiq-2.17.4/lib/sidekiq/middleware/chain.rb:127:in `invoke'
  /var/www/shared/bundle/ruby/2.0.0/gems/sidekiq-2.17.4/lib/sidekiq/processor.rb:48:in `block (2 levels) in process'
  /var/www/shared/bundle/ruby/2.0.0/gems/sidekiq-2.17.4/lib/sidekiq/processor.rb:105:in `stats'
  /var/www/shared/bundle/ruby/2.0.0/gems/sidekiq-2.17.4/lib/sidekiq/processor.rb:47:in `block in process'
  /var/www/shared/bundle/ruby/2.0.0/gems/sidekiq-2.17.4/lib/sidekiq/processor.rb:86:in `do_defer'
  /var/www/shared/bundle/ruby/2.0.0/gems/sidekiq-2.17.4/lib/sidekiq/processor.rb:37:in `process'
  /var/www/shared/bundle/ruby/2.0.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `public_send'
  /var/www/shared/bundle/ruby/2.0.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `dispatch'
  /var/www/shared/bundle/ruby/2.0.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:122:in `dispatch'
  /var/www/shared/bundle/ruby/2.0.0/gems/celluloid-0.15.2/lib/celluloid/actor.rb:322:in `block in handle_message'
  /var/www/shared/bundle/ruby/2.0.0/gems/celluloid-0.15.2/lib/celluloid/actor.rb:416:in `block in task'
  /var/www/shared/bundle/ruby/2.0.0/gems/celluloid-0.15.2/lib/celluloid/tasks.rb:55:in `block in initialize'
  /var/www/shared/bundle/ruby/2.0.0/gems/celluloid-0.15.2/lib/celluloid/tasks/task_fiber.rb:13:in `block in create'

-------------------------------
Data:
-------------------------------

  * data: {:message=>
    {"retry"=>true,
     "queue"=>"default",
     "class"=>"RunWorker",
     "args"=>[2611],
     "jid"=>"aa511a329196d43d79af4e26",
     "enqueued_at"=>1392850809.3616428,
     "error_message"=>
      "Circular dependency detected while autoloading constant Morph::DockerRunner",
     "error_class"=>"RuntimeError",
     "failed_at"=>2014-02-19 23:00:13 UTC,
     "retry_count"=>0}}
```

**Comment by benrfairless** [comment]
Thanks for raising this, and sorry it has sat without a response for so long.

We are tidying up the morph.io issue tracker. This issue dates from 2014 and, on review, looks to have gone stale (the idea has been overtaken, superseded, or not picked up in the years since), so we are closing it as part of a backlog review to keep the tracker focused on work we can realistically act on. Closing it is not a judgement that the underlying idea was wrong.

If this is still relevant to you, please reopen it or open a fresh issue with up to date detail and we will gladly take another look.

This triage was carried out with AI assistance (Claude Opus 4.8 via Claude Code) and reviewed by the OpenAustralia Foundation team.
