### ISSUE TITLE
morph-cli appears to be completely broken

### ISSUE THREAD

**Issue by mlandauer** [openaustralia/morph#569]
```
noodle:test-python matthew$ morph
Uploading and running...
/Users/matthew/.rvm/gems/ruby-2.1.1/gems/morph-cli-0.2.1/lib/morph-cli.rb:38:in `log': Unknown stream (RuntimeError)
	from /Users/matthew/.rvm/gems/ruby-2.1.1/gems/morph-cli-0.2.1/lib/morph-cli.rb:15:in `block (3 levels) in execute'
	from /Users/matthew/.rvm/gems/ruby-2.1.1/gems/morph-cli-0.2.1/lib/morph-cli.rb:14:in `each'
	from /Users/matthew/.rvm/gems/ruby-2.1.1/gems/morph-cli-0.2.1/lib/morph-cli.rb:14:in `block (2 levels) in execute'
	from /Users/matthew/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/net/protocol.rb:407:in `call_block'
	from /Users/matthew/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/net/protocol.rb:398:in `<<'
	from /Users/matthew/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/net/protocol.rb:106:in `read'
	from /Users/matthew/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/net/http/response.rb:313:in `read_chunked'
	from /Users/matthew/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/net/http/response.rb:276:in `block in read_body_0'
	from /Users/matthew/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/net/http/response.rb:250:in `inflater'
	from /Users/matthew/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/net/http/response.rb:274:in `read_body_0'
	from /Users/matthew/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/net/http/response.rb:201:in `read_body'
	from /Users/matthew/.rvm/gems/ruby-2.1.1/gems/morph-cli-0.2.1/lib/morph-cli.rb:11:in `block in execute'
	from /Users/matthew/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/net/http.rb:1415:in `block (2 levels) in transport_request'
	from /Users/matthew/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/net/http/response.rb:162:in `reading_body'
	from /Users/matthew/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/net/http.rb:1414:in `block in transport_request'
	from /Users/matthew/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/net/http.rb:1405:in `catch'
	from /Users/matthew/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/net/http.rb:1405:in `transport_request'
	from /Users/matthew/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/net/http.rb:1378:in `request'
	from /Users/matthew/.rvm/gems/ruby-2.1.1/gems/rest-client-1.7.3/lib/restclient/request.rb:270:in `net_http_do_request'
	from /Users/matthew/.rvm/gems/ruby-2.1.1/gems/rest-client-1.7.3/lib/restclient/request.rb:415:in `block in transmit'
	from /Users/matthew/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/net/http.rb:853:in `start'
	from /Users/matthew/.rvm/gems/ruby-2.1.1/gems/rest-client-1.7.3/lib/restclient/request.rb:413:in `transmit'
	from /Users/matthew/.rvm/gems/ruby-2.1.1/gems/rest-client-1.7.3/lib/restclient/request.rb:176:in `execute'
	from /Users/matthew/.rvm/gems/ruby-2.1.1/gems/rest-client-1.7.3/lib/restclient/request.rb:41:in `execute'
	from /Users/matthew/.rvm/gems/ruby-2.1.1/gems/morph-cli-0.2.1/lib/morph-cli.rb:26:in `execute'
	from /Users/matthew/.rvm/gems/ruby-2.1.1/gems/morph-cli-0.2.1/bin/morph:32:in `execute'
	from /Users/matthew/.rvm/gems/ruby-2.1.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/matthew/.rvm/gems/ruby-2.1.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/matthew/.rvm/gems/ruby-2.1.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/matthew/.rvm/gems/ruby-2.1.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/matthew/.rvm/gems/ruby-2.1.1/gems/morph-cli-0.2.1/bin/morph:63:in `<top (required)>'
	from /Users/matthew/.rvm/gems/ruby-2.1.1/bin/morph:23:in `load'
	from /Users/matthew/.rvm/gems/ruby-2.1.1/bin/morph:23:in `<main>'
	from /Users/matthew/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/matthew/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by mlandauer** [comment]
Fixed a bug in morph-cli (and released a new version of the gem) that stopped it from recognising log output from buildpack compiles.

Also, fixed a bug on the main morph project that was causing any run from morph-cli to fail because it couldn't pick up the environment variable setup because there is no attached scraper.

So, closing this as fixed.
