### ISSUE TITLE
Error installing morph-cli gem

### ISSUE THREAD

**Issue by dpschramm** [openaustralia/morph#792]
Command line output:

```
schramm-macbookpro:Documents schramm$ sudo gem install morph-cli
Password:
Fetching: thor-0.19.1.gem (100%)
Successfully installed thor-0.19.1
Fetching: unf_ext-0.0.7.1.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing morph-cli:
	ERROR: Failed to build gem native extension.

    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby extconf.rb
mkmf.rb can't find header files for ruby at /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/include/ruby.h


Gem files will remain installed in /Library/Ruby/Gems/2.0.0/gems/unf_ext-0.0.7.1 for inspection.
Results logged to /Library/Ruby/Gems/2.0.0/gems/unf_ext-0.0.7.1/ext/unf_ext/gem_make.out
```

Results from /Library/Ruby/Gems/2.0.0/gems/unf_ext-0.0.7.1/ext/unf_ext/gem_make.out
```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby extconf.rb
mkmf.rb can't find header files for ruby at /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/include/ruby.h
```

**Comment by kaydensigh** [comment]
Installing the headers solved the above problem:
```
sudo apt-get install ruby-dev
```

But running `morph` gave this output:
```
Uploading and running...
/usr/lib/ruby/2.1.0/openssl/buffering.rb:326:in `syswrite': Connection reset by peer (Errno::ECONNRESET)
	from /usr/lib/ruby/2.1.0/openssl/buffering.rb:326:in `do_write'
	from /usr/lib/ruby/2.1.0/openssl/buffering.rb:344:in `write'
	from /usr/lib/ruby/2.1.0/net/http/generic_request.rb:202:in `copy_stream'
	from /usr/lib/ruby/2.1.0/net/http/generic_request.rb:202:in `send_request_with_body_stream'
	from /usr/lib/ruby/2.1.0/net/http/generic_request.rb:132:in `exec'
	from /usr/lib/ruby/2.1.0/net/http.rb:1406:in `block in transport_request'
	from /usr/lib/ruby/2.1.0/net/http.rb:1405:in `catch'
	from /usr/lib/ruby/2.1.0/net/http.rb:1405:in `transport_request'
	from /usr/lib/ruby/2.1.0/net/http.rb:1378:in `request'
	from /var/lib/gems/2.1.0/gems/rest-client-2.0.0.rc1/lib/restclient/request.rb:326:in `net_http_do_request'
	from /var/lib/gems/2.1.0/gems/rest-client-2.0.0.rc1/lib/restclient/request.rb:498:in `block in transmit'
	from /usr/lib/ruby/2.1.0/net/http.rb:853:in `start'
	from /var/lib/gems/2.1.0/gems/rest-client-2.0.0.rc1/lib/restclient/request.rb:494:in `transmit'
	from /var/lib/gems/2.1.0/gems/rest-client-2.0.0.rc1/lib/restclient/request.rb:202:in `execute'
	from /var/lib/gems/2.1.0/gems/rest-client-2.0.0.rc1/lib/restclient/request.rb:52:in `execute'
	from /var/lib/gems/2.1.0/gems/morph-cli-0.2.2/lib/morph-cli.rb:26:in `execute'
	from /var/lib/gems/2.1.0/gems/morph-cli-0.2.2/bin/morph:32:in `execute'
	from /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /var/lib/gems/2.1.0/gems/morph-cli-0.2.2/bin/morph:63:in `<top (required)>'
	from /usr/local/bin/morph:23:in `load'
	from /usr/local/bin/morph:23:in `<main>'
```

**Comment by chris48s** [comment]
I also have the same issue as @kaydensigh:

```
Uploading and running...
/var/lib/gems/2.2.0/gems/morph-cli-0.2.2/lib/morph-cli.rb:39:in `log': Unknown stream (RuntimeError)
	from /var/lib/gems/2.2.0/gems/morph-cli-0.2.2/lib/morph-cli.rb:15:in `block (3 levels) in execute'
	from /var/lib/gems/2.2.0/gems/morph-cli-0.2.2/lib/morph-cli.rb:14:in `each'
	from /var/lib/gems/2.2.0/gems/morph-cli-0.2.2/lib/morph-cli.rb:14:in `block (2 levels) in execute'
	from /usr/lib/ruby/2.2.0/net/protocol.rb:411:in `call_block'
	from /usr/lib/ruby/2.2.0/net/protocol.rb:402:in `<<'
	from /usr/lib/ruby/2.2.0/net/protocol.rb:106:in `read'
	from /usr/lib/ruby/2.2.0/net/http/response.rb:318:in `read_chunked'
	from /usr/lib/ruby/2.2.0/net/http/response.rb:282:in `block in read_body_0'
	from /usr/lib/ruby/2.2.0/net/http/response.rb:250:in `inflater'
	from /usr/lib/ruby/2.2.0/net/http/response.rb:280:in `read_body_0'
	from /usr/lib/ruby/2.2.0/net/http/response.rb:201:in `read_body'
	from /var/lib/gems/2.2.0/gems/morph-cli-0.2.2/lib/morph-cli.rb:11:in `block in execute'
	from /usr/lib/ruby/2.2.0/net/http.rb:1423:in `block in transport_request'
	from /usr/lib/ruby/2.2.0/net/http/response.rb:162:in `reading_body'
	from /usr/lib/ruby/2.2.0/net/http.rb:1422:in `transport_request'
	from /usr/lib/ruby/2.2.0/net/http.rb:1384:in `request'
	from /var/lib/gems/2.2.0/gems/rest-client-2.0.0/lib/restclient/request.rb:497:in `net_http_do_request'
	from /var/lib/gems/2.2.0/gems/rest-client-2.0.0/lib/restclient/request.rb:770:in `block in transmit'
	from /usr/lib/ruby/2.2.0/net/http.rb:853:in `start'
	from /var/lib/gems/2.2.0/gems/rest-client-2.0.0/lib/restclient/request.rb:766:in `transmit'
	from /var/lib/gems/2.2.0/gems/rest-client-2.0.0/lib/restclient/request.rb:215:in `execute'
	from /var/lib/gems/2.2.0/gems/rest-client-2.0.0/lib/restclient/request.rb:52:in `execute'
	from /var/lib/gems/2.2.0/gems/morph-cli-0.2.2/lib/morph-cli.rb:26:in `execute'
	from /var/lib/gems/2.2.0/gems/morph-cli-0.2.2/bin/morph:32:in `execute'
	from /var/lib/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /var/lib/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /var/lib/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /var/lib/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /var/lib/gems/2.2.0/gems/morph-cli-0.2.2/bin/morph:63:in `<top (required)>'
	from /usr/local/bin/morph:23:in `load'
	from /usr/local/bin/morph:23:in `<main>'
```

**Comment by benrfairless** [comment]
Thanks for raising this, and sorry it has sat without a response for so long.

We are tidying up the morph.io issue tracker. This issue dates from 2015 and, on review, looks to have gone stale (the idea has been overtaken, superseded, or not picked up in the years since), so we are closing it as part of a backlog review to keep the tracker focused on work we can realistically act on. Closing it is not a judgement that the underlying idea was wrong.

If this is still relevant to you, please reopen it or open a fresh issue with up to date detail and we will gladly take another look.

This triage was carried out with AI assistance (Claude Opus 4.8 via Claude Code) and reviewed by the OpenAustralia Foundation team.
