### ISSUE TITLE
Bug #565 is back

### ISSUE THREAD

**Issue by pstavirs** [openaustralia/morph#805]
Opening a new bug since I can't reopen the old one (#565) -

Injecting configuration and compiling...
Injecting scraper and running...
Last date in DB: 2015-06-09
Traceback (most recent call last):
  File "scraper.py", line 15, in <module>
    page = requests.get('https://bintray.com/statistics/packageStatistics?pkgPath=/pstavirs/ostinato/'+package)
  File "/app/.heroku/python/lib/python2.7/site-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/requests/sessions.py", line 269, in request
    resp = self.send(prep, stream=stream, timeout=timeout, verify=verify, cert=cert, proxies=proxies)
  File "/app/.heroku/python/lib/python2.7/site-packages/requests/sessions.py", line 364, in send
    r = adapter.send(request, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/requests/adapters.py", line 163, in send
    raise SSLError(e)
requests.exceptions .SSLError: [Errno 1] _ssl.c:507: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

**Comment by mlandauer** [comment]
Thanks so much for putting this ticket in again!

Should be all fixed again. Sorry about the hassle. There was a change to the backend where the scraper command wasn't being run inside of a shell anymore and it was the shell that was setting the environment variable which stopped this problem from occurring. It should be all good now.

If you see this or any other problem happening please do go ahead and let us know
