### ISSUE TITLE
Morph::Runner tests failing

### ISSUE THREAD

**Issue by henare** [openaustralia/morph#807]
Wild guess is that these tests never worked on Linux or they're regressions that the OS X people didn't see because they normally don't run these tests?

```
Failures:

  1) Morph::Runner.go should magically handle a sidekiq queue restart
     Failure/Error: expect {runner.go_with_logging do |s, c|
       expected Sidekiq::Shutdown but nothing was raised
     # ./spec/lib/morph/runner_spec.rb:53:in `block (3 levels) in <top (required)>'

  2) Morph::Runner.go should handle restarting from a stopped container
     Failure/Error: expect(logs).to eq [
       
       expected: ["Injecting configuration and compiling...\n", "Injecting scraper and running...\n", "Started!\n", "1...\n", "2...\n"]
            got: ["Injecting configuration and compiling...\n", "Injecting scraper and running...\n", "Started!\n", "1...", "\n", "2...\n"]
       
       (compared using ==)
       
       Diff:
       @@ -1,6 +1,7 @@
        Injecting configuration and compiling...\n
        Injecting scraper and running...\n
        Started!\n
       -1...\n
       +1...
       +\n
        2...\n
     # ./spec/lib/morph/runner_spec.rb:131:in `block (3 levels) in <top (required)>'

  3) Morph::Runner.stop! should be able to stop a scraper running in a continuous loop
     Failure/Error: expect(Morph::DockerUtils.stopped_containers.count).to eq container_count
       
       expected: 1
            got: 2
       
       (compared using ==)
     # ./spec/lib/morph/runner_spec.rb:216:in `block (3 levels) in <top (required)>'

Finished in 57.34 seconds
263 examples, 3 failures, 2 pending

Failed examples:

rspec ./spec/lib/morph/runner_spec.rb:28 # Morph::Runner.go should magically handle a sidekiq queue restart
rspec ./spec/lib/morph/runner_spec.rb:99 # Morph::Runner.go should handle restarting from a stopped container
rspec ./spec/lib/morph/runner_spec.rb:181 # Morph::Runner.stop! should be able to stop a scraper running in a continuous loop
```

**Comment by henare** [comment]
After running it a few times trying to debug this I've had runs with no failures, 1 failure, 2 failures, or 3 failures like above.

That sounds like a test isolation problem but these failures don't look like that.

**Comment by henare** [comment]
Only 1 failure in my last run. Matthew and I talked about how it was the log line parsing and I think this failure shows that well so I'll post it:

```
  1) Morph::Runner.go should magically handle a sidekiq queue restart
     Failure/Error: expect(logs).to eq [
       
       expected: ["3...\n", "4...\n", "5...\n", "6...\n", "7...\n", "8...\n", "9...\n", "10...\n", "Finished!\n"]
            got: ["3...\n", "4...\n", "5...\n", "6...", "\n", "7...\n", "8...", "\n", "9...\n", "10...", "\n", "Finished!\n"]
       
       (compared using ==)
       
       Diff:
       
       
       @@ -1,10 +1,13 @@
        3...\n
        4...\n
        5...\n
       -6...\n
       +6...
       +\n
        7...\n
       -8...\n
       +8...
       +\n
        9...\n
       -10...\n
       +10...
       +\n
        Finished!\n
     # ./spec/lib/morph/runner_spec.rb:81:in `block (3 levels) in <top (required)>'

Finished in 58.88 seconds
263 examples, 1 failure, 2 pending
```
